apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spin-demo-new
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: my-service-push
        image: index.docker.io/bitspradp/cd_demo_spin
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
