apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spin-demo-new
  labels:
    run: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sample-app
  template:
    metadata:
      labels:
        run: sample-app
    spec:
      containers:
      - name: my-service-push
        image: index.docker.io/bitspradp/cd_demo_spin
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  run: sample-app
spec:
  selector:
    run: sample-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
