apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spin-demo-new
  labels:
    app: spinn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spinn
  template:
    metadata:
      labels:
        app: spinn
    spec:
      containers:
      - name: my-service-push
        image: index.docker.io/bitspradp/cd_demo_spin
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  app: spinn
spec:
  selector:
    app: spinn
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
